name: Release DependencyInjection packages

on:
  repository_dispatch:
  push:
    tags:
    - "DependencyInjection-v[0-9]+.[0-9]+.[0-9]+*"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY}}

jobs:

  Release:
    name: Release DependencyInjection packages
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Verify commit
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/DependencyInjection-v/}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet build src/DependencyInjection/BitzArt.TransientServiceProvider/BitzArt.TransientServiceProvider.csproj --configuration Release /p:Version=${VERSION}
          dotnet pack src/DependencyInjection/BitzArt.TransientServiceProvider/BitzArt.TransientServiceProvider.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: | 
          dotnet nuget push BitzArt.TransientServiceProvider.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}