name: Release EntityFrameworkCore.EntityBase

on:
  repository_dispatch:
  push:
    tags:
    - "EntityFrameworkCore.EntityBase-v[0-9]+.[0-9]+.[0-9]+"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY}}

jobs:

  EntityFrameworkCore-EntityBase:
    name: EntityFrameworkCore-EntityBase
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Install dotnet
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0.x'

      - name: Verify commit
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/EntityFrameworkCore.EntityBase-v/}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet build src/EntityFrameworkCore/BitzArt.EntityFrameworkCore.EntityBase/BitzArt.EntityFrameworkCore.EntityBase.csproj --configuration Release /p:Version=${VERSION}
          dotnet pack src/EntityFrameworkCore/BitzArt.EntityFrameworkCore.EntityBase/BitzArt.EntityFrameworkCore.EntityBase.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: dotnet nuget push BitzArt.EntityFrameworkCore.EntityBase.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}