name: Release MassTransit.ConsumerBase

on:
  repository_dispatch:
  push:
    tags:
    - "MassTransit.ConsumerBase-v[0-9]+.[0-9]+.[0-9]+"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY}}

jobs:

  MassTransit-ConsumerBase:
    name: MassTransit-ConsumerBase
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Verify commit
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/MassTransit.ConsumerBase-v/}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet build src/MassTransit/BitzArt.MassTransit.ConsumerBase/BitzArt.MassTransit.ConsumerBase.csproj --configuration Release /p:Version=${VERSION}
          dotnet pack src/MassTransit/BitzArt.MassTransit.ConsumerBase/BitzArt.MassTransit.ConsumerBase.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: dotnet nuget push BitzArt.MassTransit.ConsumerBase.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}