name: Release LinqExtensions

on:
  repository_dispatch:
  push:
    tags:
    - "LinqExtensions-v[0-9]+.[0-9]+.[0-9]+"

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY}}

jobs:

  LinqExtensions:
    name: LinqExtensions
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '9.x'

      - name: Verify commit
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
          git branch --remote --contains | grep origin/main

      - name: Set version
        run: echo "VERSION=${GITHUB_REF/refs\/tags\/LinqExtensions-v/}" >> $GITHUB_ENV

      - name: Build
        run: |
          dotnet build src/BitzArt.LinqExtensions/BitzArt.LinqExtensions.csproj --configuration Release /p:Version=${VERSION}
          dotnet pack src/BitzArt.LinqExtensions/BitzArt.LinqExtensions.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet build src/BitzArt.LinqExtensions.Batching/BitzArt.LinqExtensions.Batching.csproj --configuration Release /p:Version=${VERSION}
          dotnet pack src/BitzArt.LinqExtensions.Batching/BitzArt.LinqExtensions.Batching.csproj --configuration Release /p:Version=${VERSION} --no-build --output .
          dotnet build src/BitzArt.LinqExtensions.Conditional/BitzArt.LinqExtensions.Conditional.csproj --configuration Release /p:Version=${VERSION}
          dotnet pack src/BitzArt.LinqExtensions.Conditional/BitzArt.LinqExtensions.Conditional.csproj --configuration Release /p:Version=${VERSION} --no-build --output .

      - name: Push
        run: | 
          dotnet nuget push BitzArt.LinqExtensions.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.LinqExtensions.Batching.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}
          dotnet nuget push BitzArt.LinqExtensions.Conditional.${VERSION}.nupkg --source https://api.nuget.org/v3/index.json --api-key ${NUGET_APIKEY}